In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

## read the dataset

In [3]:
X_set = pd.read_csv('X_train.csv') #remove the headline automatically
Y_set = pd.read_csv('Y_train.csv')
print(X_set.shape, Y_set.shape)
X_set.head(3) #to check whether data read correctlly, return the first 3 rows of datasets
X_set.isnull().sum(0)

(1212, 833) (1212, 2)

id        0
x0       94
x1       98
x2       95
x3      106
       ...
x827    103
x828     97
x829    100
x830     88
x831    121
Length: 833, dtype: int64

In [4]:
# print(X_set.describe()) #show some statistics of dataset

In [5]:
# separate the other attributes from the predicting attribute
X_set = X_set.drop(['id'], axis=1) #remove the id column
Y_set = Y_set['y'] #remove the id column

X_set.shape
X_set.head(3)

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,10.891876,832442.812375,20585.544083,1028.369495,1.163780e+06,9.199135,597900.477629,NaN,1.144294e+06,785176.201298,...,1.024198e+06,-855.549602,12176.073427,10.647729,10.916371,1220.065443,8.566724,1.036263e+06,85338.558539,103088.664210
1,11.512994,832442.898114,NaN,1012.624877,1.028911e+06,10.906408,597900.458612,8127.016078,1.099166e+06,785176.258299,...,1.086806e+06,-787.397942,10493.095660,10.586492,9.463962,917.094909,10.231822,1.007163e+06,95695.020645,105161.109422
2,11.052185,832442.896307,20585.512844,1003.953827,9.231756e+05,9.212979,597900.426764,10738.092422,1.027863e+06,785176.223468,...,1.018533e+06,-906.997242,10959.516944,10.769287,10.342160,637.027802,10.705461,1.019955e+06,80253.299882,104177.051666

## Dataset processing

In [6]:
# do Normalization
X_set = (X_set-X_set.min())/(X_set.max()-X_set.min())
# another normalization method
# X_set = (X_set-X_set.mean())/X_set.std()   
X_set.head(20)

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.671513,0.038048,0.704819,0.283301,0.742406,0.384317,0.968128,NaN,0.791909,0.250335,...,0.241736,0.563679,0.432692,0.589777,0.609244,0.445293,0.313577,0.362915,0.211016,0.308463
1,0.770354,0.897546,NaN,0.125719,0.535428,0.680530,0.777597,0.327139,0.725075,0.821083,...,0.869915,0.615437,0.357152,0.533112,0.392115,0.258967,0.562242,0.071669,0.391171,0.516304
2,0.697023,0.879426,0.391507,0.038934,0.373160,0.386719,0.458500,0.517681,0.619477,0.472322,...,0.184891,0.524607,0.378087,0.702259,0.523402,0.086727,0.632975,0.199699,0.122556,0.417615
3,0.790895,NaN,NaN,0.046123,0.408105,0.445786,0.694986,0.720988,0.827230,0.786720,...,0.470693,0.445058,0.642270,0.438115,0.561191,0.380106,0.575570,0.855114,NaN,0.274150
4,0.594372,0.229011,0.834443,NaN,0.484488,0.248992,0.427188,0.675011,0.671809,0.146022,...,0.310078,0.434820,0.709739,NaN,NaN,0.451457,0.564971,0.248307,0.497643,0.516569
5,0.393441,0.745244,0.750365,0.429555,0.612631,0.573744,0.538431,0.444119,0.542422,0.725350,...,0.201641,0.612919,0.462438,0.510227,0.529996,0.451447,0.682104,NaN,0.299688,0.909538
6,0.513004,0.082817,0.705859,0.014213,0.481119,0.571161,0.552909,0.615606,0.509748,0.943604,...,0.381649,0.509320,0.531793,0.385884,0.538337,0.356702,0.561714,0.547745,0.481525,0.604055
7,0.500136,0.201866,0.331550,0.130879,0.277263,0.589952,0.846611,0.415661,0.727776,0.536242,...,0.508185,0.514356,0.476883,0.846418,0.601059,0.311815,0.584919,0.570132,0.448159,0.108038
8,0.609064,NaN,0.900911,NaN,0.368798,0.580435,0.575278,0.404641,0.616271,0.881391,...,0.813199,NaN,0.401746,NaN,NaN,0.276775,0.396583,0.817372,0.285689,0.587306
9,0.501173,0.891950,0.178228,0.741159,0.559307,0.582064,0.239388,0.388219,0.385523,0.404721,...,0.177841,0.471952,0.550556,0.295412,NaN,0.295230,0.526491,NaN,0.195370,0.891387
10,NaN,0.022178,NaN,0.139409,0.366002,0.829720,0.880937,0.511548,0.388703,0.567866,...,0.326259,0.613814,0.494110,0.156316,0.494226,0.445263,0.436797,0.944807,0.044654,0.253214
11,0.399982,0.554337,0.653785,0.999765,0.503615,0.612424,0.707821,0.371219,0.438599,0.289966,...,0.028059,0.767558,0.362530,0.684772,0.119736,0.383791,0.224874,0.778298,0.651623,NaN
12,0.439863,0.573168,0.194261,NaN,0.495332,0.451704,0.439884,0.539864,0.754313,0.010555,...,0.373882,0.628998,0.460744,0.154723,0.783528,0.303221,0.692333,0.856827,0.389914,0.705679
13,0.263824,NaN,0.304603,0.663309,0.482987,0.418805,0.432254,0.416318,0.503295,0.671313,...,0.053197,0.657085,0.400094,0.720898,0.439205,0.277974,0.445382,0.133453,0.435679,0.595749
14,0.621239,0.374222,NaN,NaN,0.544934,0.380145,0.905181,0.697265,0.695864,0.737392,...,0.732193,0.272371,0.622476,0.451677,0.467768,0.459428,0.499077,0.826167,0.734600,NaN
15,0.657597,0.757103,0.739676,0.335358,0.488709,0.507444,0.728770,0.332033,0.270092,0.476738,...,NaN,0.640176,0.379240,0.250590,0.424294,0.186377,0.839220,0.705956,0.537265,0.780318
16,0.450660,0.786582,0.935166,0.395398,0.405857,NaN,0.659610,0.623126,0.554278,0.336654,...,0.219824,0.374504,0.623415,0.199565,0.514067,0.542438,0.585020,0.573084,0.504905,0.375633
17,0.340578,0.885890,0.814242,0.306007,0.461429,0.743654,0.372523,0.550298,0.412821,0.572759,...,0.966895,0.506384,0.722717,NaN,0.375898,0.428653,0.469767,0.326015,0.495323,0.632428
18,0.663015,0.638208,0.897287,NaN,0.308780,0.432978,0.056441,0.528766,0.633320,0.793590,...,0.267996,0.547102,0.490986,0.798176,0.461098,0.218980,0.529648,0.438800,0.533302,0.149003
19,NaN,0.793379,0.045410,0.653461,0.562593,0.742669,0.676278,0.574964,0.612614,0.723363,...,0.101187,0.453464,0.590990,NaN,0.519833,0.285383,0.545092,0.290973,0.302332,0.414286

In [7]:
#use each col's mean to fill the NAN default value
# X_set = X_set.fillna(X_set.mean())
X_set = X_set.fillna(0)
X_set.head(7)

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.671513,0.038048,0.704819,0.283301,0.742406,0.384317,0.968128,0.000000,0.791909,0.250335,...,0.241736,0.563679,0.432692,0.589777,0.609244,0.445293,0.313577,0.362915,0.211016,0.308463
1,0.770354,0.897546,0.000000,0.125719,0.535428,0.680530,0.777597,0.327139,0.725075,0.821083,...,0.869915,0.615437,0.357152,0.533112,0.392115,0.258967,0.562242,0.071669,0.391171,0.516304
2,0.697023,0.879426,0.391507,0.038934,0.373160,0.386719,0.458500,0.517681,0.619477,0.472322,...,0.184891,0.524607,0.378087,0.702259,0.523402,0.086727,0.632975,0.199699,0.122556,0.417615
3,0.790895,0.000000,0.000000,0.046123,0.408105,0.445786,0.694986,0.720988,0.827230,0.786720,...,0.470693,0.445058,0.642270,0.438115,0.561191,0.380106,0.575570,0.855114,0.000000,0.274150
4,0.594372,0.229011,0.834443,0.000000,0.484488,0.248992,0.427188,0.675011,0.671809,0.146022,...,0.310078,0.434820,0.709739,0.000000,0.000000,0.451457,0.564971,0.248307,0.497643,0.516569
5,0.393441,0.745244,0.750365,0.429555,0.612631,0.573744,0.538431,0.444119,0.542422,0.725350,...,0.201641,0.612919,0.462438,0.510227,0.529996,0.451447,0.682104,0.000000,0.299688,0.909538
6,0.513004,0.082817,0.705859,0.014213,0.481119,0.571161,0.552909,0.615606,0.509748,0.943604,...,0.381649,0.509320,0.531793,0.385884,0.538337,0.356702,0.561714,0.547745,0.481525,0.604055

In [8]:
print("X_set.shape:", X_set.shape)
print("Y_set.shape:", Y_set.shape)

X_set.shape: (1212, 832)
Y_set.shape: (1212,)

In [9]:
X_test = pd.read_csv('X_test.csv')
index = X_test['id']
X_test = X_test.drop(['id'], axis=1) #remove the id column
X_test = (X_test-X_test.min())/(X_test.max()-X_test.min())
X_test = X_test.fillna(0)
X_test.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,0.415325,0.308207,0.648817,0.000000,0.476479,0.620551,0.124536,0.681166,0.496761,0.041624,...,0.493262,0.420391,0.488855,0.489549,0.380597,0.395869,0.395899,0.062109,0.000000,0.667910
1,0.794794,0.176575,0.355775,0.390984,0.441792,0.744044,0.938155,0.640432,0.523259,0.241013,...,0.640248,0.658509,0.758826,0.395947,0.605191,0.205733,0.650677,0.644282,0.478676,0.000000
2,0.719223,0.116671,0.374241,0.820564,0.565056,0.000000,0.519187,0.560098,0.278645,0.091203,...,0.340600,0.564318,0.636767,0.101375,0.261571,0.268253,0.348724,0.072303,0.568313,0.339338
3,0.497432,0.122117,0.548181,0.638467,0.505861,0.494749,0.458250,0.668078,0.553008,0.872168,...,0.643372,0.000000,0.701828,0.694664,0.301473,0.360003,0.428010,0.765690,0.000000,0.050036
4,0.593177,0.634560,0.092934,0.132439,0.370644,0.660278,0.186446,0.652828,0.562102,0.757922,...,0.709802,0.387576,0.683560,0.649590,0.562130,0.306665,0.349911,0.980459,0.621300,0.484766

## Regression Method

In [16]:
LR = LinearRegression()


X_set.isnull().sum(0)
#X_set[X_set.isnull().values == True]
#X_set.shape
#print(X_set)
#print("\n\n",Y_set)
LR.fit(X_set,Y_set)
y_prediction = LR.predict(X_test)
Y_prediction = LR.predict(X_set)
#print(y_prediction)
prediction_results = pd.DataFrame(data=y_prediction,columns=['y'])
# Using DataFrame.insert() to add a column
index = [i for i in range(len(prediction_results))]
prediction_results.insert(0,"id",index)
  
# Observe the result
prediction_results
prediction_results.to_csv('result_0.csv',index = False)

prediction_results = pd.DataFrame(data=Y_prediction,columns=['Y'])
# Using DataFrame.insert() to add a column
index = [i for i in range(len(prediction_results))]
prediction_results.insert(0,"id",index)
  
# Observe the result
prediction_results
prediction_results.to_csv('result_1.csv',index = False)